### ISSUE TITLE
Can't get hmac-sha256.js & enc-base64-min.js

### ISSUE THREAD

**Issue by franklin168** [primaryobjects/TokenAuthMVC#1]
Hi 

I can't get get [hmac-sha256.js](http://crypto-js.googlecode.com/svn/tags/3.0.2/build/rollups/hmac-sha256.js) & [enc-base64-min.js ](http://crypto-js.googlecode.com/svn/tags/3.0.2/build/components/enc-base64-min.js).The link is broken ?

**Comment by primaryobjects** [comment]
Try these [hmac-sha256.js](https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/hmac-sha256.js) and [enc-base64-min.js](https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/enc-base64-min.js)
